[aliyun-oss]
access_key_id = 'your id here'
access_key_secret = 'your key here'
endpoint = 'https://oss-cn-shenzhen.aliyuncs.com'
bucket_name = 'bucket-feishu'

[tongyi-tingwu]
# 和阿里的配置一样
access_key_id = 'your id here'
access_key_secret = 'your key here'
AppKey = "your app key here"

[dify]
dify_workflow_api = "xxx"